### ISSUE TITLE
Inlining bug

### ISSUE THREAD

**Issue by bradunov** [dimitriv/Ziria#125]
There is a bug in the inlining code. The example is in tests/backend/inline.wpl test, added in e7df5059b078a. Currently, there is a print line that prevents code from inlining, and the code produces correct results. However, once the print line is removed the inliner will kick in and the output will be incorrect.

**Comment by dimitriv** [comment]
Wow Sid! That was fast, thanks SO much!

**Comment by siddhanathan** [comment]
No problem :)

**Comment by bradunov** [comment]
Thanks a lot indeed!
