### ISSUE TITLE
Eliminate Text.PrettyPrint.Mainland 

### ISSUE THREAD

**Issue by edsko** [dimitriv/Ziria#63]
Currently we use `Text.PrettyPrint.HughesPJ` for some stuff and `Text.PrettyPrint.Mainland` for some other stuff. This is confusing and since the two libraries are not compatible (both introduce their own `Doc` type) it's also inconvenient.

**Comment by dimitriv** [comment]
Done that. Text.PrettyPrint.Mainland is now only used for printing C declarations from Language.C.Quote in Main.hs. The rest of the compiler consistently uses HughesPJ. Relevant commit is 0041bdaec31c1db8cad9
