### ISSUE TITLE
Don't "partially evaluate" prints with multiple arguments

### ISSUE THREAD

**Issue by edsko** [dimitriv/Ziria#94]
The interpreter will execute prints with statically known arguments at compile time rather than at runtime, but if you write something like

```
print "The value of a is", a
```

in the source, this gets translated to _two_ print statements in the AST, and consequently the interpreter will execute the first but not the second. We should change the AST so that print takes multiple arguments, and then change the interpreter so that it only executes the whole thing of _all_ arguments are statically known.

**Comment by dimitriv** [comment]
I will close this as the commit above addresses the issue. I think we can clean up he print state in the Interpreter but I will refrain from doing this in case we need to revert some of this in the future.

**Comment by edsko** [comment]
With the change of having multiple arguments to print I think you could revert the behaviour of the interpreter. The point was that you could have print statements in code that was meant to be executed completely statically (computation of tables etc) so that you could debug it. The behaviour was confusing because of the single-arugment problem, but that's gone now? Anyway, just my 2c :)

**Comment by edsko** [comment]
(Note that with your change, if you do insert print statements in otherwise statically evaluable code, the code will not be executed at compile time.)
